#!/bin/bash
# update-status.sh — regenerate docs/STATUS.md from quality JSON reports
# Trigger: PostToolUse or post-commit. Exit 0 always.

set -euo pipefail

STATUSFILE="docs/STATUS.md"

# Write header
cat > "$STATUSFILE" << 'HEADER'
# Chapter Status

> Auto-generated by `update-status.sh`. Do not edit manually.

| # | Chapter / Lecture | Draft | Scored | Clarity | Rigor | Completeness | Pedagogy | Style | Released |
|---|-------------------|-------|--------|---------|-------|--------------|----------|-------|----------|
HEADER

# Find all chapters
for dir in $(ls -d book/chapters/[0-9][0-9]-*/ 2>/dev/null | sort); do
    [ -d "$dir" ] || continue
    DIRNAME=$(basename "$dir")
    NUM="${DIRNAME:0:2}"
    NAME="${DIRNAME:3}"
    TITLE=$(echo "$NAME" | tr '-' ' ' | sed 's/\b\(.\)/\u\1/g')

    # Check if chapter has real content
    CHFILE="$dir/chapter.tex"
    DRAFT="No"
    if [ -f "$CHFILE" ] && ! grep -q "invoke /draft-chapter" "$CHFILE" 2>/dev/null; then
        DRAFT="Yes"
    fi

    # Check quality report
    SAFE=$(echo "book/chapters/${DIRNAME}/chapter" | tr '/' '_')
    JSONFILE="docs/quality/${SAFE}-score.json"
    SCORED="No"
    C="-"; R="-"; CO="-"; P="-"; S="-"
    RELEASED="No"

    if [ -f "$JSONFILE" ]; then
        SCORED="Yes"
        C=$(python3 -c "import json; d=json.load(open('$JSONFILE')); print(d['scores']['clarity'])" 2>/dev/null || echo "?")
        R=$(python3 -c "import json; d=json.load(open('$JSONFILE')); print(d['scores']['rigor'])" 2>/dev/null || echo "?")
        CO=$(python3 -c "import json; d=json.load(open('$JSONFILE')); print(d['scores']['completeness'])" 2>/dev/null || echo "?")
        P=$(python3 -c "import json; d=json.load(open('$JSONFILE')); print(d['scores']['pedagogy'])" 2>/dev/null || echo "?")
        S=$(python3 -c "import json; d=json.load(open('$JSONFILE')); print(d['scores']['style'])" 2>/dev/null || echo "?")

        # Check if released based on all passing
        PASS=$(python3 -c "import json; d=json.load(open('$JSONFILE')); print('Yes' if d.get('pass', False) else 'No')" 2>/dev/null || echo "No")
        RELEASED="$PASS"
    fi

    echo "| $NUM | $TITLE | $DRAFT | $SCORED | $C | $R | $CO | $P | $S | $RELEASED |" >> "$STATUSFILE"
done

echo "STATUS.md updated."
exit 0
